import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useState } from "react";
import { Alert, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { Badge, Button, Card, Divider, EmptyState, Loading, Screen, Section } from "../../components/ui";
import { buscarCliente, listarUnidadesCliente } from "../../services/clientes.service";
import { buscarFaturasCliente } from "../../services/faturas.service";
import { Colors, Radius, Spacing, Typography } from "../../theme";

const moeda = (v: unknown) => Number(v ?? 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const documento = (valor: unknown) => { const numeros = String(valor ?? "").replace(/\D/g, ""); if (numeros.length === 11) return numeros.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, "$1.$2.$3-$4"); if (numeros.length === 14) return numeros.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, "$1.$2.$3/$4-$5"); return String(valor ?? ""); };

export default function ClienteDetalhe() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [cliente, setCliente] = useState<any>(); const [faturas, setFaturas] = useState<any[]>([]); const [unidades, setUnidades] = useState<any[]>([]); const [buscaUnidades, setBuscaUnidades] = useState(""); const [loading, setLoading] = useState(true);
  const carregar = useCallback(async () => { try { const [c, u] = await Promise.all([buscarCliente(id), listarUnidadesCliente(id)]); setCliente(c); setUnidades(u ?? []); setFaturas(c.uc ? await buscarFaturasCliente(c.uc) : []); } finally { setLoading(false); } }, [id]);
  useFocusEffect(useCallback(() => { carregar(); }, [carregar]));
  if (loading) return <Loading />;
  if (!cliente) return <Screen><View style={styles.state}><EmptyState icon="person-outline" title="Cliente não encontrado" subtitle="Não foi possível carregar este cadastro." /></View></Screen>;
  const economia = faturas.reduce((t, f) => t + Number(f.economia_real ?? f.economia ?? 0), 0);
  const termoUnidade = buscaUnidades.trim().toLocaleLowerCase("pt-BR");
  const unidadesFiltradas = unidades.filter((unidade) => `${unidade.numero} ${unidade.titular} ${unidade.endereco} ${unidade.distribuidora}`.toLocaleLowerCase("pt-BR").includes(termoUnidade));

  function whatsapp() { const numero = String(cliente.whatsapp ?? cliente.telefone ?? "").replace(/\D/g, ""); if (!numero) return Alert.alert("WhatsApp não informado", "Adicione um telefone no cadastro do cliente."); Linking.openURL(`https://wa.me/${numero.startsWith("55") ? numero : `55${numero}`}?text=${encodeURIComponent(`Olá ${cliente.nome}, estou entrando em contato sobre sua energia.`)}`); }

  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><View style={styles.avatar}><Text style={styles.avatarText}>{cliente.nome?.charAt(0)?.toUpperCase()}</Text></View><View style={styles.headingText}><Text style={styles.eyebrow}>CLIENTE</Text><Text style={styles.title}>{cliente.nome}</Text><Text style={styles.subtitle}>{cliente.uc ? `UC ${cliente.uc}` : "Sem unidade vinculada"}</Text></View><Badge label={cliente.status ?? "ATIVO"} variant="success" /></View>
    <Card><Info icon="flash-outline" label="Unidade consumidora principal" value={cliente.uc ? `UC ${cliente.uc}` : "Não informada"} />{cliente.cpf ? <><Divider /><Info icon="person-outline" label="CPF / CNPJ" value={documento(cliente.cpf)} /></> : null}<Divider /><Info icon="call-outline" label="Telefone / WhatsApp" value={cliente.telefone || "Não informado"} /><Divider /><Info icon="mail-outline" label="E-mail" value={cliente.email || "Não informado"} /><Divider /><Info icon="location-outline" label="Endereço" value={cliente.endereco || "Não informado"} /><Divider /><Info icon="business-outline" label="Distribuidora" value={cliente.distribuidora || "Concessionária"} /></Card>
    <View style={styles.actions}><Button title="Editar" icon={<Ionicons name="create-outline" size={19} color={Colors.surface} />} style={styles.action} onPress={() => router.push({ pathname: "/clientes/editar", params: { id } })} /><Button title="WhatsApp" icon={<Ionicons name="logo-whatsapp" size={19} color={Colors.surface} />} style={[styles.action, styles.whatsapp]} onPress={whatsapp} /></View>
    <Section title="Unidades consumidoras"><View><View style={styles.unitActions}><View style={styles.search}><Ionicons name="search-outline" size={20} color={Colors.subtitle} /><TextInput value={buscaUnidades} onChangeText={setBuscaUnidades} placeholder="Buscar por UC, titular ou endereço" placeholderTextColor={Colors.subtitle} style={styles.searchInput} /></View><TouchableOpacity accessibilityLabel="Adicionar unidade consumidora" onPress={() => router.push({ pathname: "/unidades/nova", params: { clienteId: id } })} style={styles.addUnit}><Ionicons name="add" size={22} color={Colors.surface} /></TouchableOpacity></View>{unidadesFiltradas.length ? unidadesFiltradas.map((unidade) => <Card key={unidade.id}><View style={styles.unitRow}><View style={styles.unitIcon}><Ionicons name="flash-outline" size={21} color={Colors.primary} /></View><View style={styles.unitInfo}><Text style={styles.unitNumber}>UC {unidade.numero}</Text><Text numberOfLines={1} style={styles.unitDetail}>{unidade.titular || unidade.endereco || unidade.distribuidora || "Concessionária"}</Text></View><Badge label={unidade.status ?? "ATIVA"} variant={unidade.status === "INATIVA" ? "danger" : "success"} /></View></Card>) : <EmptyState icon="flash-outline" title={buscaUnidades ? "Nenhuma unidade encontrada" : "Nenhuma unidade vinculada"} subtitle={buscaUnidades ? "Altere os termos da busca." : "Adicione a primeira unidade consumidora deste cliente."} />}</View></Section>
    <Section title="Economia"><Card><Text style={styles.summaryLabel}>Economia acumulada</Text><Text style={styles.summaryValue}>{moeda(economia)}</Text><Text style={styles.summaryDetail}>{faturas.length} fatura{faturas.length === 1 ? "" : "s"} processada{faturas.length === 1 ? "" : "s"}</Text></Card></Section>
    <Section title="Histórico de faturas">{faturas.length ? faturas.map((f) => <Pressable key={f.id} onPress={() => f.id && router.push(`/faturas/${f.id}`)}><Card><View style={styles.invoice}><View style={styles.invoiceIcon}><Ionicons name="receipt-outline" size={21} color={Colors.primary} /></View><View style={styles.invoiceInfo}><Text style={styles.invoiceTitle}>{f.referencia}</Text><Text style={styles.invoiceDetail}>Economia {moeda(f.economia_real ?? f.economia)}</Text></View><Text style={styles.invoiceValue}>{moeda(f.valor_total_unificado ?? f.valor_total)}</Text><Ionicons name="chevron-forward" size={18} color={Colors.subtitle} /></View></Card></Pressable>) : <EmptyState icon="receipt-outline" title="Nenhuma fatura processada" subtitle="As faturas deste cliente aparecerão aqui." />}</Section>
  </ScrollView></Screen>;
}

function Info({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={styles.info}><View style={styles.infoIcon}><Ionicons name={icon} size={20} color={Colors.primary} /></View><View style={styles.infoText}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
const styles = StyleSheet.create({ content: { padding: Spacing.lg, paddingBottom: Spacing.xxl }, state: { flex: 1, justifyContent: "center", padding: Spacing.lg }, heading: { flexDirection: "row", alignItems: "center", marginBottom: Spacing.lg }, avatar: { width: 58, height: 58, alignItems: "center", justifyContent: "center", borderRadius: Radius.round, backgroundColor: Colors.primaryLight }, avatarText: { color: Colors.primaryDark, fontSize: Typography.title, fontWeight: "800" }, headingText: { flex: 1, marginHorizontal: Spacing.sm }, eyebrow: { color: Colors.primary, fontSize: Typography.small, fontWeight: "800", letterSpacing: 1.1 }, title: { marginTop: 3, color: Colors.text, fontSize: Typography.section, fontWeight: "800" }, subtitle: { marginTop: 3, color: Colors.subtitle }, info: { minHeight: 58, flexDirection: "row", alignItems: "center" }, infoIcon: { width: 42, alignItems: "center" }, infoText: { flex: 1, marginLeft: Spacing.sm }, infoLabel: { color: Colors.subtitle, fontSize: Typography.small }, infoValue: { marginTop: 3, color: Colors.text, fontWeight: "700" }, actions: { flexDirection: "row", gap: Spacing.sm, marginBottom: Spacing.lg }, action: { flex: 1 }, whatsapp: { backgroundColor: Colors.success }, unitActions: { flexDirection: "row", gap: Spacing.sm, marginBottom: Spacing.md }, search: { minHeight: 52, flex: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: Spacing.md, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.lg, backgroundColor: Colors.surface }, searchInput: { flex: 1, marginLeft: Spacing.xs, color: Colors.text }, addUnit: { width: 52, height: 52, alignItems: "center", justifyContent: "center", borderRadius: Radius.lg, backgroundColor: Colors.primary }, unitRow: { flexDirection: "row", alignItems: "center" }, unitIcon: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: Radius.md, backgroundColor: Colors.primaryLight }, unitInfo: { flex: 1, marginHorizontal: Spacing.sm }, unitNumber: { color: Colors.text, fontSize: Typography.body, fontWeight: "800" }, unitDetail: { marginTop: 3, color: Colors.subtitle, fontSize: Typography.small }, summaryLabel: { color: Colors.subtitle }, summaryValue: { marginTop: Spacing.xs, color: Colors.primaryDark, fontSize: 30, fontWeight: "800" }, summaryDetail: { marginTop: Spacing.xs, color: Colors.subtitle }, invoice: { flexDirection: "row", alignItems: "center" }, invoiceIcon: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: Radius.md, backgroundColor: Colors.primaryLight }, invoiceInfo: { flex: 1, marginHorizontal: Spacing.sm }, invoiceTitle: { color: Colors.text, fontWeight: "700" }, invoiceDetail: { marginTop: 4, color: Colors.subtitle, fontSize: Typography.small }, invoiceValue: { marginRight: Spacing.sm, color: Colors.text, fontWeight: "700" } });
