import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import PortalBrandLogo from "../../components/brand/PortalBrandLogo";
import { ElasticScrollView as ScrollView, Screen } from "../../components/ui";
import { useAuth } from "../../contexts/AuthContext";
import { obterPainelComercial, PainelComercial } from "../../services/comercial.service";
import { Colors, Radius, Shadows, Spacing, Typography } from "../../theme";

const moeda = (value: unknown) => Number(value ?? 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function HomeComercial() {
  const insets = useSafeAreaInsets();
  const { usuario } = useAuth(); const [data,setData]=useState<PainelComercial|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{setData(await obterPainelComercial());}catch(error:any){setData(null);Alert.alert("Não foi possível carregar a gestão comercial",error?.response?.data?.message??"Verifique se o backend e a migração comercial estão atualizados.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  if(usuario?.perfil!=="ADMIN"){router.replace("/selecionar-unidade");return null;}
  const resumo=data?.resumo;
  return <Screen><StatusBar backgroundColor="#083D31" barStyle="light-content"/><View style={[styles.header,{marginTop:-insets.top,paddingTop:insets.top+10}]}><PortalBrandLogo height={45} width={164}/><View style={styles.headerCopy}><Text style={styles.headerLabel}>GESTÃO COMERCIAL</Text><Text style={styles.headerUser}>{usuario.nome}</Text></View><TouchableOpacity accessibilityLabel="Abrir perfil" onPress={()=>router.push("/(tabs)/perfil")} style={styles.profile}><Ionicons name="person-outline" size={22} color="#FFF"/></TouchableOpacity></View><TouchableOpacity accessibilityLabel="Trocar ambiente de gestão" activeOpacity={0.82} onPress={()=>router.replace("/admin/escolher-area" as any)} style={styles.environmentSwitch}><View style={styles.environmentCurrent}><Ionicons name="briefcase-outline" size={14} color="#A7F3D0"/><Text style={styles.environmentLabel}>Gestão comercial</Text></View><Text style={styles.environmentAction}>Trocar ambiente</Text><Ionicons name="chevron-forward" size={14} color="#F6CC32"/></TouchableOpacity>
    <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} colors={[Colors.primary]}/> }>
      <View style={styles.heading}><Text style={styles.eyebrow}>ADMINISTRAÇÃO DO SOFTWARE</Text><Text style={styles.title}>Painel comercial</Text><Text style={styles.subtitle}>Acompanhe a comercialização e o acesso dos geradores.</Text></View>
      {loading&&!data?<ActivityIndicator color={Colors.primary}/>:<View style={styles.metrics}><Metric icon="people-outline" label="Assinaturas" value={String(resumo?.total??0)}/><Metric icon="checkmark-circle-outline" label="Ativas" value={String(resumo?.ativas??0)} green/><Metric icon="alert-circle-outline" label="Inadimplentes" value={String(resumo?.inadimplentes??0)} danger/><Metric icon="trending-up-outline" label="Receita mensal" value={moeda(resumo?.receitaMensalPrevista)}/></View>}
      <Text style={styles.section}>ACESSO RÁPIDO</Text><View style={styles.menu}>
        <Menu icon="business-outline" title="Geradores e assinaturas" description="Planos, cobranças e situação dos acessos." onPress={()=>router.push("/geradores/gestao" as any)}/>
        <Menu icon="person-add-outline" title="Convidar gerador" description="Crie um convite seguro para uma nova conta." onPress={()=>router.push("/geradores/convidar")}/>
        <Menu icon="document-text-outline" title="Contratos e termos" description={`${data?.documentos.length??0} documentos comerciais cadastrados.`} onPress={()=>router.push("/geradores/gestao" as any)}/>
        <Menu icon="sunny-outline" title="Alternar para Gestão de Usinas" description="Abra o ambiente operacional e escolha uma usina." onPress={()=>router.replace("/selecionar-unidade")}/>
        <Menu icon="person-circle-outline" title="Perfil administrativo" description="Dados, segurança e alternância de ambientes." onPress={()=>router.push("/(tabs)/perfil")}/>
      </View>
      <Text style={styles.section}>RESUMO DA OPERAÇÃO COMERCIAL</Text><View style={styles.summary}><View><Text style={styles.summaryValue}>{data?.geradores.length??0}</Text><Text style={styles.summaryLabel}>contas geradoras</Text></View><View><Text style={styles.summaryValue}>{data?.planos.filter(p=>p.ativo).length??0}</Text><Text style={styles.summaryLabel}>planos ativos</Text></View><View><Text style={styles.summaryValue}>{data?.documentos.filter(d=>d.ativo).length??0}</Text><Text style={styles.summaryLabel}>documentos publicados</Text></View></View>
    </ScrollView></Screen>;
}
function Metric({icon,label,value,green,danger}:any){return <View style={styles.metric}><Ionicons name={icon} size={21} color={danger?Colors.danger:green?Colors.success:Colors.primary}/><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>}
function Menu({icon,title,description,onPress}:any){return <TouchableOpacity onPress={onPress} style={styles.menuRow}><View style={styles.menuIcon}><Ionicons name={icon} size={22} color={Colors.primary}/></View><View style={styles.menuCopy}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuDescription}>{description}</Text></View><Ionicons name="chevron-forward" size={20} color={Colors.subtitle}/></TouchableOpacity>}
const styles=StyleSheet.create({header:{minHeight:90,flexDirection:"row",alignItems:"center",paddingHorizontal:Spacing.lg,paddingTop:10,paddingBottom:10,backgroundColor:"#083D31"},headerCopy:{flex:1,marginLeft:Spacing.sm},headerLabel:{color:"#86EFAC",fontSize:10,fontWeight:"900",letterSpacing:1},headerUser:{marginTop:3,color:"#FFF",fontSize:13,fontWeight:"800"},profile:{width:42,height:42,alignItems:"center",justifyContent:"center",borderRadius:Radius.round,backgroundColor:"rgba(255,255,255,.12)"},environmentSwitch:{minHeight:34,flexDirection:"row",alignItems:"center",paddingHorizontal:Spacing.lg,backgroundColor:"#0A503F"},environmentCurrent:{flex:1,flexDirection:"row",alignItems:"center",gap:6},environmentLabel:{color:"#D8F0E3",fontSize:11,fontWeight:"700"},environmentAction:{marginRight:3,color:"#F6CC32",fontSize:10,fontWeight:"900"},content:{padding:Spacing.lg,paddingBottom:Spacing.xxl*2},heading:{marginBottom:Spacing.lg},eyebrow:{color:Colors.primary,fontSize:10,fontWeight:"900",letterSpacing:1.1},title:{marginTop:4,color:Colors.text,fontSize:Typography.title,fontWeight:"900"},subtitle:{marginTop:4,color:Colors.subtitle,lineHeight:19},metrics:{flexDirection:"row",flexWrap:"wrap",gap:Spacing.sm},metric:{width:"48%",padding:Spacing.md,borderRadius:Radius.lg,backgroundColor:Colors.surface,...Shadows.card},metricLabel:{marginTop:8,color:Colors.subtitle,fontSize:11,fontWeight:"800"},metricValue:{marginTop:4,color:Colors.text,fontSize:20,fontWeight:"900"},section:{marginTop:Spacing.xl,marginBottom:Spacing.sm,color:Colors.subtitle,fontSize:10,fontWeight:"900",letterSpacing:1},menu:{overflow:"hidden",borderRadius:Radius.xl,backgroundColor:Colors.surface,...Shadows.card},menuRow:{minHeight:76,flexDirection:"row",alignItems:"center",paddingHorizontal:Spacing.md,borderBottomWidth:1,borderBottomColor:Colors.border},menuIcon:{width:42,height:42,alignItems:"center",justifyContent:"center",borderRadius:Radius.md,backgroundColor:Colors.primaryLight},menuCopy:{flex:1,marginHorizontal:Spacing.sm},menuTitle:{color:Colors.text,fontSize:14,fontWeight:"900"},menuDescription:{marginTop:3,color:Colors.subtitle,fontSize:12,lineHeight:17},summary:{flexDirection:"row",justifyContent:"space-between",padding:Spacing.lg,borderRadius:Radius.xl,backgroundColor:"#D9E9E1"},summaryValue:{color:Colors.primaryDark,fontSize:23,fontWeight:"900",textAlign:"center"},summaryLabel:{maxWidth:90,marginTop:3,color:Colors.subtitle,fontSize:10,textAlign:"center"}});
