type Audience = "gerador" | "consumidor" | "ambos";
type GuideEntry = { audience: Audience; match: RegExp; answer: string };

// Respostas extraídas dos fluxos e rótulos reais do aplicativo. Não incluem dados pessoais.
const GUIDE: GuideEntry[] = [
  { audience: "gerador", match: /\b(cadastr|adicion|nova|criar).*(usina)\b|\b(usina).*(cadastr|adicion|nova|criar)\b/, answer: "Para cadastrar uma usina, abra a lista de usinas e escolha Manual ou Via fatura. Depois confira a UC geradora e os dados da usina antes de salvar." },
  { audience: "gerador", match: /\b(cadastr|adicion|novo|criar).*(cliente|consumidor)\b|\b(cliente|consumidor).*(cadastr|adicion|novo|criar)\b/, answer: "Na aba Clientes, cadastre os dados do consumidor e confira nome, contato, documento e endereço. Depois vincule a UC e, quando os dados estiverem corretos, envie o convite para o acesso." },
  { audience: "gerador", match: /\b(cadastr|adicion|vincul|nova|criar).*(uc|unidade consumidora)\b|\b(uc|unidade consumidora).*(cadastr|adicion|vincul|nova|criar)\b/, answer: "Para adicionar uma UC, abra Unidades consumidoras e escolha o cadastro manual ou por fatura. Confira o número da instalação e o vínculo com cliente e usina antes de seguir para o contrato." },
  { audience: "gerador", match: /\b(convite|convidar|acesso do cliente)\b/, answer: "O fluxo começa pelo cadastro do cliente e da UC. Revise os dados na ficha do cliente e use a opção de convite para que ele crie o acesso; não compartilhe senha pelo assistente." },
  { audience: "gerador", match: /\b(fatur|fatura).*(pdf)\b|\b(pdf).*(fatur|fatura)\b/, answer: "Na aba Faturamento, escolha Faturamento via PDF, selecione a conta da concessionária e revise o resultado. A UC precisa estar cadastrada; um PDF protegido pode pedir a senha do próprio arquivo." },
  { audience: "gerador", match: /\b(faturamento manual|fatura manual|preencher.*cobranca)\b/, answer: "Em Faturamento, escolha Faturamento manual para preencher os dados da cobrança. Confira UC, competência, vencimento, consumo e valores antes de emitir." },
  { audience: "gerador", match: /\b(producao|geracao).*(pdf|importar|informar)\b|\b(pdf).*(producao|geracao)\b/, answer: "Para informar produção por PDF, use o botão no card Geração do mês da Home ou na lista de usinas. Confira se a UC geradora foi reconhecida no documento." },
  { audience: "gerador", match: /\b(automatic|email|e-mail).*(usina|producao|geradora)\b|\b(usina|producao|geradora).*(automatic|email|e-mail)\b/, answer: "No card Geração do mês da Home, Gerenciar recebimento de dados automático configura a conta geradora. Isso atualiza a produção, sem criar cobrança para o cliente; é separado do faturamento automático das UCs." },
  { audience: "gerador", match: /\b(faturamento automatico|fatura automatica|recebimento automatico)\b/, answer: "Na aba Faturamento, Faturamento automático configura o recebimento das contas das UCs por e-mail. Para a UC geradora e produção, use Gerenciar recebimento de dados automático no card Geração do mês da Home." },
  { audience: "gerador", match: /\b(minuta|locador|vigencia|gerar contrato)\b/, answer: "Depois de cadastrar cliente, UC e usina, revise os dados contratuais e gere a minuta em Contrato. Confira especialmente as partes, os endereços, a titularidade e a vigência antes de solicitar assinatura." },
  { audience: "gerador", match: /\b(cancelamento|cancelar contrato)\b/, answer: "Os pedidos e a análise de cancelamento ficam em Contratos. Consulte o contrato e o status do pedido antes de decidir; o assistente não cancela automaticamente." },
  { audience: "gerador", match: /\b(renovacao|renovar contrato)\b/, answer: "A renovação é tratada em Contratos. Revise as condições e a minuta atualizada antes de encaminhar para o aceite do cliente." },
  { audience: "gerador", match: /\b(pix|chave pix|transferencia|saque)\b/, answer: "Em Financeiro, a chave Pix pode ser validada e salva após conferir o titular. Transferências exigem autorização e confirmação; eu posso orientar, mas não as executo." },
  { audience: "gerador", match: /\b(operacao|fechamento|rateio|ocupacao)\b/, answer: "Na aba Operação você acompanha geração, energia alocada, disponibilidade, ocupação, receita prevista e faturas por competência. Confira a usina selecionada antes de interpretar os números." },
  { audience: "gerador", match: /\b(comercial|plano|assinatura do gerador)\b/, answer: "O ambiente comercial reúne geradores, planos e assinaturas. A área Meu plano permite consultar a assinatura do gerador; não altero planos nem cobro valores pelo assistente." },
  { audience: "ambos", match: /\b(trocar ambiente|alternar ambiente|trocar usina|trocar uc)\b/, answer: "Use Trocar ambiente para mudar a área de trabalho e Trocar usina ou Trocar UC para mudar o contexto dos dados. Antes de consultar valores ou contratos, confirme o contexto selecionado." },
  { audience: "ambos", match: /\b(notificac|aviso|alerta)\b/, answer: "Abra o sino de Notificações para acompanhar avisos e usar as ações disponíveis naquela tela. Nem todo aviso significa que uma operação foi concluída; confira o status no detalhe." },
  { audience: "ambos", match: /\b(perfil|meus dados|endereco|senha|foto de perfil)\b/, answer: "Abra Perfil para revisar seus dados, endereço, foto e opções de segurança. Confira o que foi salvo antes de sair da tela." },
  { audience: "ambos", match: /\b(tutorial|video|ajuda)\b/, answer: "Em Tutoriais, escolha o vídeo do processo que deseja acompanhar. Assistir a um vídeo não executa cadastros, cobranças, contratos ou transferências." },
  { audience: "consumidor", match: /\b(assinar|aceitar|contrato|revisao)\b/, answer: "Na aba Contrato você pode ler a minuta, verificar revisões e seguir as etapas de assinatura ou aceite disponíveis. Leia as condições antes de confirmar; o assistente não assina por você." },
  { audience: "consumidor", match: /\b(fatura|cobranca|pix|boleto|pagamento)\b/, answer: "Abra Faturas para ver as cobranças da UC selecionada, valores e formas de pagamento disponíveis. Confirme a referência e o beneficiário antes de pagar." },
  { audience: "consumidor", match: /\b(economia|desconto|historico de economia)\b/, answer: "Abra Economia para consultar o histórico e a economia acumulada da UC selecionada. Para valores atuais, confira o período exibido no aplicativo." },
  { audience: "consumidor", match: /\b(conta de luz|concessionaria|pdf da cemig)\b/, answer: "Em Conta de luz você encontra os PDFs da concessionária disponíveis para a UC selecionada. Se o documento estiver em preparação, aguarde a disponibilização no aplicativo." },
  { audience: "gerador", match: /\b(inversor|inversores|monitoramento solar)\b/, answer: "Abra a usina e a seção Inversores para consultar ou configurar o monitoramento disponível. Confira o equipamento e a usina antes de interpretar os dados." },
  { audience: "gerador", match: /\b(fechamento|competencia|rateio)\b/, answer: "Na aba Operação, consulte a competência e o fechamento da usina. Revise geração, energia alocada e UCs antes de confirmar qualquer resultado." },
  { audience: "gerador", match: /\b(colaborador|equipe|permissao)\b/, answer: "Abra Colaboradores para consultar a equipe, convites e permissões. Um colaborador pode ter acesso limitado a dados financeiros e administrativos." },
  { audience: "gerador", match: /\b(meu plano|upgrade|plano atual)\b/, answer: "Abra Meu plano para consultar recursos, situação da assinatura e opções disponíveis. Qualquer mudança de plano ou pagamento precisa ser confirmada por você." },
  { audience: "gerador", match: /\b(empresa parceira|geradores|gestao comercial|administracao comercial)\b/, answer: "No ambiente Comercial, a administração acompanha geradores, assinaturas, pagamentos e empresas parceiras conforme suas permissões. Confirme o ambiente antes de consultar dados." },
  { audience: "gerador", match: /\b(fatura anexada|anexo do cliente|subir fatura do cliente)\b/, answer: "Na ficha do cliente, use Faturas anexadas para revisar documentos enviados. Confira titularidade e UC antes de usar uma fatura em cadastro ou cobrança." },
  { audience: "gerador", match: /\b(endereco do locador|dados do locador|titularidade da usina)\b/, answer: "Na minuta da unidade, revise os dados do locador, inclusive documento e endereço, conforme o perfil do gerador e a titularidade aplicável. Não presuma que sejam os dados do consumidor." },
  { audience: "ambos", match: /\b(criar conta|cadastro de acesso|verificar email|esqueci a senha|redefinir senha)\b/, answer: "O acesso é criado ou recuperado pelas telas de login, verificação de e-mail e redefinição de senha. Use seu próprio e-mail; nunca envie senha ou código de verificação ao assistente." },
  { audience: "ambos", match: /\b(busca|pesquisar|encontrar uma tela|onde fica)\b/, answer: "Use a pesquisa do aplicativo ou o menu para encontrar a função pelo nome. Atalhos rápidos podem mudar de posição, então prefira o nome da seção." },
  { audience: "ambos", match: /\b(sobre o app|versao|atualizacao|historico de atualizacoes)\b/, answer: "Em Sobre o app você encontra a versão e o histórico de melhorias exibidos nesta instalação. Se não corresponderem ao comportamento atual, confira se há atualização disponível." },
];

export function guideAppAnswer(normalizedQuestion: string, variant: "gerador" | "consumidor") {
  return GUIDE.find(item => (item.audience === "ambos" || item.audience === variant) && item.match.test(normalizedQuestion))?.answer;
}
