type Repasse = "REPASSAR" | "ABSORVER" | string;
type TarifaHistorica = { referencia?: string | null; tarifa_scee?: number; tarifa_gd2?: number };
type Props = { desconto:string; tipoGd:string; modalidadeFaturamento?:string|null; consumoProjetado?:string|number|null; dadosFatura?:Record<string,any>|null; projetarConsumoIntegral?:boolean; tarifaSceeReferencia?:number; tarifaGd2Referencia?:number; historicoTarifasGd2?:TarifaHistorica[]; gd1:Repasse; gd2:Repasse; fioB:Repasse };
const FIO_B_PROVISORIO=0.13;

export default function RealDiscountInfoWeb({desconto,tipoGd,modalidadeFaturamento,consumoProjetado,dadosFatura,projetarConsumoIntegral=false,tarifaSceeReferencia=0,tarifaGd2Referencia=0,historicoTarifasGd2=[],gd1,gd2,fioB}:Props){
  const value=Math.max(0,Math.min(100,numberValue(desconto))),tariff=100-value,type=String(tipoGd??"").toUpperCase(),transferred:string[]=[];
  if((!type||type==="GD1"||type==="MISTA")&&gd1==="REPASSAR")transferred.push("disponibilidade GD I");
  if((!type||type==="GD2"||type==="MISTA")&&gd2==="REPASSAR")transferred.push("disponibilidade GD II");
  if((!type||type==="GD2"||type==="MISTA")&&fioB==="REPASSAR")transferred.push("Fio B");
  const semLeituraGd=Boolean(dadosFatura)&&!hasGdReading(dadosFatura),consumoIntegral=projetarConsumoIntegral?(numberFrom(dadosFatura,"consumo_kwh","consumoKwh","consumo_faturado","consumoFaturado","consumo")||numberValue(consumoProjetado)):0,simularContaConvencional=semLeituraGd&&consumoIntegral>0&&["GD1","GD2","MISTA"].includes(type),tarifaDaCompetencia=findMonthlyTariff(dadosFatura,historicoTarifasGd2);
  const preview=calculatePreview({data:dadosFatura,discount:value,billingMode:modalidadeFaturamento,type,gd1,gd2,fioB,projectedConsumption:simularContaConvencional?consumoIntegral:0,sceeReference:numberValue(tarifaDaCompetencia?.tarifa_scee)||tarifaSceeReferencia,gd2Reference:numberValue(tarifaDaCompetencia?.tarifa_gd2)||tarifaGd2Referencia}),percent=(n:number)=>`${n.toLocaleString("pt-BR",{maximumFractionDigits:2})}%`,estimate=preview?percent(preview.realDiscount):"0,00%",detail=preview?`${simularContaConvencional?`${consumoIntegral.toLocaleString("pt-BR",{maximumFractionDigits:2})} kWh simulados. `:""}${money(preview.savings)} de economia sobre ${money(preview.discountBase)} de energia cheia.${invoiceReference(dadosFatura)}`:"A projeção precisa do consumo, da tarifa cheia e da modalidade GD da usina.";
  return <section className="real-discount-info"><header><i>∑</i><div><strong>Como calculamos o desconto real</strong><p>O percentual contratado é aplicado à energia; o real considera tudo que o cliente efetivamente paga.</p></div></header><div className="discount-formula"><article><small>{simularContaConvencional?"SIMULAÇÃO COM 100% DO CONSUMO":preview?"PROJEÇÃO PELA ÚLTIMA FATURA":"DADOS INSUFICIENTES"}</small><b>{estimate}</b><span>{detail}</span></article><div><span><small>DESCONTO CONTRATADO</small><b>{percent(value)}</b></span><span><small>TARIFA ANDRADE</small><b>{percent(tariff)} da tarifa cheia</b></span></div><hr/><small>ECONOMIA REAL</small><strong>Valor sem Andrade − total unificado</strong><hr/><small>DESCONTO REAL</small><strong>Economia real ÷ valor da energia cheia × 100</strong></div><p className="discount-impact">{transferred.length?`O desconto parte de ${percent(value)}, mas ${transferred.join(" e ")} permanecem com o cliente.`:`A usina assume os custos selecionados; o desconto tende a se aproximar dos ${percent(value)} contratados.`}</p><em>{preview?"Em conta sem GD, a tarifa GD vem da mesma competência da usina ou da última competência válida disponível.":"Vincule uma conta com dados de consumo para gerar a simulação."}</em></section>;
}
function numberValue(value:unknown){if(typeof value==="number")return Number.isFinite(value)?value:0;const text=String(value??"").trim(),normalized=text.includes(",")?text.replace(/\./g,"").replace(",","."):text;const parsed=Number(normalized);return Number.isFinite(parsed)?parsed:0}
function numberFrom(data:Record<string,any>|null|undefined,...keys:string[]){let found=0;for(const key of keys){const raw=data?.[key];if(raw===undefined||raw===null||raw==="")continue;const value=numberValue(raw);found=value;if(value!==0)return value}return found}
function money(value:number){return value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function invoiceReference(data:Record<string,any>|null|undefined){const raw=String(data?.referencia??data?.competencia??"").trim();if(!raw)return"";const match=/^(\d{4})-(\d{2})/.exec(raw);return` Base: ${match?`${match[2]}/${match[1]}`:raw}.`}
function hasGdReading(data:Record<string,any>|null|undefined){return numberFrom(data,"energia_compensada","energiaCompensada","energia_compensada_gd1","energiaCompensadaGD1","energia_compensada_gd2","energiaCompensadaGD2","energia_injetada","energiaInjetada")>0}
function sortableMonth(value:unknown){const text=String(value??"").trim(),iso=/^(\d{4})[-/](\d{1,2})/.exec(text);if(iso)return Number(iso[1])*100+Number(iso[2]);const br=/^(\d{1,2})[-/](\d{4})/.exec(text);return br?Number(br[2])*100+Number(br[1]):0}
function findMonthlyTariff(data:Record<string,any>|null|undefined,history:TarifaHistorica[]){const valid=history.filter(item=>numberValue(item.tarifa_scee)>0&&numberValue(item.tarifa_gd2)>0).sort((a,b)=>sortableMonth(b.referencia)-sortableMonth(a.referencia));if(!valid.length)return null;const month=sortableMonth(data?.referencia??data?.competencia);if(!month)return valid[0];return valid.find(item=>sortableMonth(item.referencia)===month)??valid.find(item=>sortableMonth(item.referencia)<=month)??valid[0]}
function calculatePreview({data,discount,billingMode,type,gd1,gd2,fioB,projectedConsumption,sceeReference,gd2Reference}:{data?:Record<string,any>|null;discount:number;billingMode?:string|null;type:string;gd1:Repasse;gd2:Repasse;fioB:Repasse;projectedConsumption:number;sceeReference:number;gd2Reference:number}){
  if(!data)return null;let fullTariff=numberFrom(data,"tarifa_cheia","tarifaCheia");const utilityValue=numberFrom(data,"valor_cemig","valorCemig","valor_concessionaria","valorConcessionaria","valor_total","valorTotal"),energyGd1=numberFrom(data,"energia_compensada_gd1","energiaCompensadaGD1"),energyGd2=numberFrom(data,"energia_compensada_gd2","energiaCompensadaGD2"),compensated=numberFrom(data,"energia_compensada","energiaCompensada")||energyGd1+energyGd2,injected=numberFrom(data,"energia_injetada","energiaInjetada"),baseKwh=projectedConsumption>0?projectedConsumption:String(billingMode??"COMPENSACAO").toUpperCase()==="INJECAO"?injected:compensated;if(fullTariff<=0&&baseKwh>0)fullTariff=utilityValue/baseKwh;if(fullTariff<=0||utilityValue<=0||baseKwh<=0)return null;
  const franchise=numberFrom(data,"franquia_disponibilidade_kwh","franquiaDisponibilidadeKwh"),tariffWithoutTax=numberFrom(data,"tarifa_disponibilidade_sem_impostos","tarifaDisponibilidadeSemImpostos"),availabilityGd1=numberFrom(data,"custo_disponibilidade_gd1","custoDisponibilidadeGD1")||franchise*tariffWithoutTax,availabilityGd2=numberFrom(data,"custo_disponibilidade_gd2","custoDisponibilidadeGD2","custo_disponibilidade","custoDisponibilidade")||Math.max(0,franchise*(fullTariff-tariffWithoutTax)),savedWire=numberFrom(data,"diferenca_fio_b","diferencaFioB")||numberFrom(data,"valor_absorvido_fio_b","valorAbsorvidoFioB")+numberFrom(data,"diferenca_fio_b_repassada","diferencaFioBRepassada"),scee=numberFrom(data,"tarifa_scee","tarifaScee")||sceeReference||fullTariff,gd2Tariff=numberFrom(data,"tarifa_gd","tarifaGD2","tarifaGD")||gd2Reference,wireEnergy=energyGd2>0?energyGd2:projectedConsumption,usesGd2=type==="GD2"||type==="MISTA"||energyGd2>0,usesGd1=type==="GD1"||type==="MISTA"||(!usesGd2&&energyGd1>0),wire=savedWire>0?savedWire:wireEnergy>0&&scee>gd2Tariff&&gd2Tariff>0?wireEnergy*(scee-gd2Tariff):usesGd2&&wireEnergy>0?wireEnergy*scee*FIO_B_PROVISORIO:0,availability=usesGd2?availabilityGd2:availabilityGd1,absorbedAvailability=(usesGd2?gd2==="ABSORVER":usesGd1&&gd1==="ABSORVER")?availability:0,absorbedWire=usesGd2&&fioB==="ABSORVER"?wire:0,reference=baseKwh*fullTariff,andradeValue=Math.max(0,reference*(1-discount/100)-absorbedAvailability-absorbedWire),projectedUtility=projectedConsumption>0?availability+wire:numberFrom(data,"valor_energia_concessionaria","valorEnergiaConcessionaria")||utilityValue,savings=Math.max(0,reference-(projectedUtility+andradeValue));return reference>0?{savings,discountBase:reference,realDiscount:savings/reference*100}:null;
}
