import { Router } from "express";
import { exigirAutenticacao, exigirOperacaoComercial, exigirSuperAdministradorAndrade } from "../../middlewares/auth.middleware";
import * as controller from "./comercial.controller";

const router = Router();
router.get("/planos-publicos", controller.planosPublicos);
router.get("/minha-assinatura", exigirAutenticacao, controller.minhaAssinatura);
router.post("/minha-assinatura/checkout", exigirAutenticacao, controller.checkoutMinhaAssinatura);
router.use(exigirAutenticacao);
router.get("/painel", exigirOperacaoComercial, controller.painel);
router.use(exigirSuperAdministradorAndrade);
router.post("/planos", controller.criarPlano);
router.put("/planos/:id", controller.atualizarPlano);
router.get("/financeiro", controller.financeiro);
router.put("/financeiro", controller.configurarFinanceiro);
router.post("/financeiro/transferencias", controller.transferirFinanceiro);
router.post("/assinaturas", controller.contratar);
router.patch("/assinaturas/:id/status", controller.status);
router.patch("/assinaturas/:id/arquivo", controller.arquivar);
router.post("/assinaturas/:id/cobrancas", controller.cobrar);
router.get("/assinaturas/:id/cobrancas", controller.cobrancas);
export default router;
