import { brazilianNumber, calculateProjection, findMonthlyTariff, hasGdReading, projectedConsumptionFrom, type Repasse, type TarifaHistorica } from "./realDiscountCalculator";

type Props = { desconto: string; tipoGd: string; modalidadeFaturamento?: string | null; consumoProjetado?: string | number | null; energiaInjetadaProjetada?: number; faturaSomenteAndrade?: boolean; dadosFatura?: Record<string, any> | null; projetarConsumoIntegral?: boolean; tarifaSceeReferencia?: number; tarifaGd2Referencia?: number; historicoTarifasGd2?: TarifaHistorica[]; gd1: Repasse; gd2: Repasse; fioB: Repasse };

export default function RealDiscountInfoWeb({ desconto, tipoGd, modalidadeFaturamento, consumoProjetado, energiaInjetadaProjetada = 0, faturaSomenteAndrade = false, dadosFatura, projetarConsumoIntegral = false, tarifaSceeReferencia = 0, tarifaGd2Referencia = 0, historicoTarifasGd2 = [], gd1, gd2, fioB }: Props) {
  const discount = Math.max(0, Math.min(100, brazilianNumber(desconto))), type = String(tipoGd ?? "").toUpperCase(), transferred: string[] = [];
  if ((type === "GD1" || type === "MISTA") && gd1 === "REPASSAR") transferred.push("disponibilidade GD I");
  if ((type === "GD2" || type === "MISTA") && gd2 === "REPASSAR") transferred.push("disponibilidade GD II");
  if ((type === "GD2" || type === "MISTA") && fioB === "REPASSAR") transferred.push("Fio B");
  const unknownGd = !["GD1", "GD2", "MISTA"].includes(type), noGdReading = Boolean(dadosFatura) && !hasGdReading(dadosFatura);
  const fullConsumption = projetarConsumoIntegral ? projectedConsumptionFrom(dadosFatura) || Math.max(0, brazilianNumber(consumoProjetado)) : 0;
  const conventionalSimulation = noGdReading && fullConsumption > 0, noProjectionData = !dadosFatura || (noGdReading && !conventionalSimulation);
  if (unknownGd) { if (gd1 === "REPASSAR") transferred.push("disponibilidade GD I"); if (gd2 === "REPASSAR") transferred.push("disponibilidade GD II"); if (fioB === "REPASSAR") transferred.push("Fio B"); }
  const monthlyTariff = findMonthlyTariff(dadosFatura, historicoTarifasGd2);
  const preview = noProjectionData ? null : calculateProjection({ data: dadosFatura, discount, billingMode: modalidadeFaturamento, type, gd1, gd2, fioB, projectedConsumption: conventionalSimulation ? fullConsumption : 0, projectedInjectedEnergy: energiaInjetadaProjetada, sceeReference: brazilianNumber(monthlyTariff?.tarifa_scee) || tarifaSceeReferencia, gd2Reference: brazilianNumber(monthlyTariff?.tarifa_gd2) || tarifaGd2Referencia });
  const detail = noProjectionData ? "Esta conta ainda não possui energia compensada GD I/GD II nem energia injetada. A projeção permanece zerada até chegar uma fatura com GD." : preview ? `${conventionalSimulation ? `${formatKwh(fullConsumption)} compensados (100% do consumo). ` : ""}${money(preview.savings)} de economia sobre ${money(preview.discountBase)} de energia cheia. ${repasseSummary(preview)}${faturaSomenteAndrade ? " A conta da concessionária permanece separada." : ""}${invoiceReference(dadosFatura)}` : unknownGd ? "A modalidade GD será confirmada pela usina." : "A projeção precisa do consumo, da tarifa cheia e dos componentes da conta.";
  const impact = noProjectionData ? "As configurações ficam disponíveis, mas a projeção depende de uma leitura GD ou de uma conta convencional com consumo para simulação." : unknownGd ? "A modalidade GD será identificada pela usina. Sem essa informação, a projeção não cria percentuais artificiais." : transferred.length ? `O desconto parte de ${percent(discount)}, mas ${transferred.join(" e ")} permanecem com o cliente.` : `A usina assume os custos selecionados; o desconto tende a se aproximar dos ${percent(discount)} contratados.`;
  return <section className="real-discount-info"><header><i>∑</i><div><strong>Como calculamos o desconto real</strong><p>O percentual contratado é aplicado à energia; o real considera tudo que o cliente efetivamente paga.</p></div></header><div className="discount-formula"><article><small>{noProjectionData ? "PROJEÇÃO AGUARDANDO GD" : conventionalSimulation ? "PROJEÇÃO COM 100% DO CONSUMO" : preview ? "PROJEÇÃO PELA ÚLTIMA FATURA" : "DADOS INCOMPLETOS"}</small><b>{preview ? percent(preview.realDiscount) : "0,00%"}</b><span>{detail}</span></article><div><span><small>DESCONTO CONTRATADO</small><b>{percent(discount)}</b></span><span><small>TARIFA ANDRADE</small><b>{percent(100 - discount)} da tarifa cheia</b></span></div><hr/><small>ECONOMIA REAL</small><strong>Valor sem Andrade − total pago com Andrade</strong><hr/><small>DESCONTO REAL</small><strong>Economia real ÷ valor total sem Andrade × 100</strong></div><p className="discount-impact">{impact}</p><em>{preview ? faturaSomenteAndrade ? "A projeção soma a conta da concessionária e a cobrança Andrade, mesmo em documentos separados." : "A projeção mantém a última fatura como base e recalcula cada escolha em tempo real." : "Importe uma fatura com dados energéticos para calcular esta porcentagem."}</em></section>;
}

function percent(value: number) { return `${value.toLocaleString("pt-BR", { maximumFractionDigits: 2 })}%`; }
function money(value: number) { return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function formatKwh(value: number) { return `${value.toLocaleString("pt-BR", { maximumFractionDigits: 2 })} kWh`; }
function invoiceReference(data: Record<string, any> | null | undefined) { const raw = String(data?.referencia ?? data?.competencia ?? "").trim(); if (!raw) return ""; const match = /^(\d{4})-(\d{2})/.exec(raw); return ` Base: ${match ? `${match[2]}/${match[1]}` : raw}.`; }
function repasseSummary(preview: NonNullable<ReturnType<typeof calculateProjection>>) { const parts: string[] = []; if (preview.availabilityCost > 0) parts.push(preview.absorbedAvailability > 0 ? `${money(preview.absorbedAvailability)} de disponibilidade absorvida` : `${money(preview.availabilityCost)} de disponibilidade repassada`); if (preview.wireBCost > 0) parts.push(preview.absorbedWireB > 0 ? `${money(preview.absorbedWireB)} de Fio B ${preview.estimatedWireB ? "estimado e " : ""}absorvido` : `${money(preview.wireBCost)} de Fio B ${preview.estimatedWireB ? "estimado e " : ""}repassado`); if (!preview.usesGd2) parts.push("GD I sem defasagem de Fio B; energia compensada pela tarifa cheia"); return parts.length ? `${parts.join(" e ")}. ` : ""; }
