export default function RealDiscountInfoWeb({ desconto, tipoGd, gd1, gd2, fioB }: { desconto: string; tipoGd: string; gd1: string; gd2: string; fioB: string }) {
  const parsed = Number(String(desconto).replace(",",".")); const value = Number.isFinite(parsed) ? Math.max(0,Math.min(100,parsed)) : 0;
  const tariff = 100-value; const type=tipoGd.toUpperCase(); const transferred:string[]=[];
  if ((!type||type==="GD1"||type==="MISTA")&&gd1==="REPASSAR") transferred.push("disponibilidade GD I");
  if ((!type||type==="GD2"||type==="MISTA")&&gd2==="REPASSAR") transferred.push("disponibilidade GD II");
  if ((!type||type==="GD2"||type==="MISTA")&&fioB==="REPASSAR") transferred.push("Fio B");
  const percent=(n:number)=>`${n.toLocaleString("pt-BR",{maximumFractionDigits:2})}%`;
  const estimate=transferred.length?`Menor que ${percent(value)}`:type?`Próximo de ${percent(value)}`:`Até ${percent(value)}`;
  return <section className="real-discount-info"><header><i>∑</i><div><strong>Como calculamos o desconto real</strong><p>O percentual contratado é aplicado à energia; o real considera tudo que o cliente efetivamente paga.</p></div></header><div className="discount-formula"><article><small>DESCONTO REAL ESTIMADO</small><b>{estimate}</b><span>{transferred.length?`Os custos repassados (${transferred.join(" e ")}) reduzem a economia percebida pelo cliente.`:"A Andrade absorve os custos selecionados; outros encargos ainda podem variar."}</span></article><div><span><small>DESCONTO CONTRATADO</small><b>{percent(value)}</b></span><span><small>TARIFA ANDRADE</small><b>{percent(tariff)} da tarifa cheia</b></span></div><hr/><small>ECONOMIA REAL</small><strong>Valor sem Andrade − total unificado</strong><hr/><small>DESCONTO REAL</small><strong>Economia real ÷ valor da energia cheia × 100</strong></div><p className="discount-impact">{transferred.length?`O desconto parte de ${percent(value)}, mas ${transferred.join(" e ")} permanecem com o cliente. Essas parcelas reduzem o desconto real da competência.`:`A usina assume disponibilidade e Fio B aplicáveis. Assim, o desconto real tende a se aproximar dos ${percent(value)} contratados.`}</p><em>Vincule uma fatura com histórico para calcular a porcentagem exata desta UC.</em></section>;
}
